// ── SKINS (fonte única: cliente renderiza, servidor valida preço/unlock) ──────
// `pattern` é a textura procedural desenhada por client/src/theme/patterns.js dentro do disco (nada de imagem:
// tudo canvas, assado uma vez por skin/tier). `accent` é a 2ª cor do padrão; `ring` desenha o anel de Saturno.
// Padrões: plain·stripes·clouds·storm·swirl·galaxy·craters·continents·lava·ice·poison·aurora·checker·crystal·
// rings2·eye·sparkle·void·nebula·metal·scales·plasma. Ids nunca mudam (o banco guarda o que cada um comprou).
// @ts-check
export const RARITY_LABELS={"free":"Grátis","common":"Comum","rare":"Raro","epic":"Épico","legendary":"Lendário","earned":"Conquista","secret":"Secreto"};
export const RARITY_ORDER=["free","common","rare","epic","legendary","earned","secret"];
export const RARITY_COLORS={"free":"#aaaaaa","common":"#88ccff","rare":"#44aaff","epic":"#aa44ff","legendary":"#ffcc00","earned":"#44ffaa","secret":"#ff4488"};
/** @type {Array<{id:number,name:string,emoji:string,rarity:string,price:number,color:string,ring:boolean,glow:string,desc:string,pattern?:string,accent?:string,unlockKey?:string}>} */
export const SKINS=[
  {"id": 0, "name": "Planeta Padrão", "emoji": "🪐", "rarity": "free", "price": 0, "color": "#4ECDC4", "ring": false, "glow": "#4ECDC4", "desc": "Seu ponto de partida", "pattern": "clouds", "accent": "#a9f3ec"},
  {"id": 1, "name": "Marte", "emoji": "🔴", "rarity": "common", "price": 200, "color": "#c1440e", "ring": false, "glow": "#ff6644", "desc": "O planeta vermelho", "pattern": "craters", "accent": "#e07a4a"},
  {"id": 2, "name": "Netuno", "emoji": "🔵", "rarity": "common", "price": 200, "color": "#4060c8", "ring": false, "glow": "#6080ff", "desc": "Azul profundo", "pattern": "storm", "accent": "#8fd0ff"},
  {"id": 3, "name": "Vênus", "emoji": "🟡", "rarity": "common", "price": 250, "color": "#e8c87a", "ring": false, "glow": "#ffdd88", "desc": "Dourado nebuloso", "pattern": "clouds", "accent": "#fff0c0"},
  {"id": 4, "name": "Mercúrio", "emoji": "⚫", "rarity": "common", "price": 200, "color": "#9090a8", "ring": false, "glow": "#aaaacc", "desc": "Cinzento rochoso", "pattern": "craters", "accent": "#c9c9dd"},
  {"id": 5, "name": "Júpiter", "emoji": "🟠", "rarity": "common", "price": 300, "color": "#c88c5a", "ring": false, "glow": "#ffaa66", "desc": "O gigante das listras", "pattern": "stripes", "accent": "#d1442f"},
  {"id": 6, "name": "Terra", "emoji": "🌍", "rarity": "common", "price": 300, "color": "#4a9eff", "ring": false, "glow": "#44aaff", "desc": "Lar doce lar", "pattern": "continents", "accent": "#46c46b"},
  {"id": 7, "name": "Lua", "emoji": "🌕", "rarity": "common", "price": 150, "color": "#d0d0d8", "ring": false, "glow": "#eeeeff", "desc": "Satélite clássico", "pattern": "craters", "accent": "#f0f0ff"},
  {"id": 8, "name": "Cometa", "emoji": "☄️", "rarity": "common", "price": 250, "color": "#88ccff", "ring": false, "glow": "#aaddff", "desc": "Velocidade cósmica", "pattern": "sparkle", "accent": "#ffffff"},
  {"id": 9, "name": "Asteroide", "emoji": "🪨", "rarity": "common", "price": 200, "color": "#886644", "ring": false, "glow": "#aa8866", "desc": "Rocha espacial", "pattern": "craters", "accent": "#c0a080"},
  {"id": 10, "name": "Saturno", "emoji": "💛", "rarity": "rare", "price": 600, "color": "#c8a060", "ring": true, "glow": "#ffcc66", "desc": "Com anel dourado", "pattern": "stripes", "accent": "#e8d29a"},
  {"id": 11, "name": "Urano", "emoji": "🩵", "rarity": "rare", "price": 700, "color": "#7ab8d4", "ring": true, "glow": "#88ddff", "desc": "Gigante de gelo", "pattern": "clouds", "accent": "#dff4ff"},
  {"id": 12, "name": "Estrela Cadente", "emoji": "🌠", "rarity": "rare", "price": 800, "color": "#ffffaa", "ring": false, "glow": "#ffffff", "desc": "Faísca do universo", "pattern": "sparkle", "accent": "#ffffff"},
  {"id": 13, "name": "Nebulosa Rosa", "emoji": "🌸", "rarity": "rare", "price": 750, "color": "#ff88bb", "ring": false, "glow": "#ffaad0", "desc": "Nuvem cósmica", "pattern": "nebula", "accent": "#ffd0e8"},
  {"id": 14, "name": "Nebulosa Verde", "emoji": "💚", "rarity": "rare", "price": 750, "color": "#44dd88", "ring": false, "glow": "#66ffaa", "desc": "Gás esmeralda", "pattern": "nebula", "accent": "#baffd8"},
  {"id": 15, "name": "Pulsar", "emoji": "⚡", "rarity": "rare", "price": 900, "color": "#ddff44", "ring": false, "glow": "#eeff66", "desc": "Emite energia", "pattern": "plasma", "accent": "#ffffff"},
  {"id": 16, "name": "Anã Branca", "emoji": "⭐", "rarity": "rare", "price": 850, "color": "#eeeeff", "ring": false, "glow": "#ffffff", "desc": "Núcleo estelar", "pattern": "plasma", "accent": "#cfe6ff"},
  {"id": 17, "name": "Planeta Gelo", "emoji": "🧊", "rarity": "rare", "price": 700, "color": "#aaddff", "ring": false, "glow": "#cceeFF", "desc": "Congelado no espaço", "pattern": "ice", "accent": "#ffffff"},
  {"id": 18, "name": "Planeta Lava", "emoji": "🌋", "rarity": "rare", "price": 800, "color": "#ff4422", "ring": false, "glow": "#ff6600", "desc": "Fervendo de energia", "pattern": "lava", "accent": "#ffcc33"},
  {"id": 19, "name": "Planeta Veneno", "emoji": "☠️", "rarity": "rare", "price": 700, "color": "#88ff44", "ring": false, "glow": "#aaff66", "desc": "Venenoso e letal", "pattern": "poison", "accent": "#3fbf2f"},
  {"id": 20, "name": "Buraco Negro", "emoji": "🕳️", "rarity": "epic", "price": 1500, "color": "#110022", "ring": true, "glow": "#aa00ff", "desc": "Absorve tudo", "pattern": "void", "accent": "#aa00ff"},
  {"id": 21, "name": "Quasar", "emoji": "🔮", "rarity": "epic", "price": 2000, "color": "#cc44ff", "ring": false, "glow": "#ee66ff", "desc": "Núcleo galáctico", "pattern": "plasma", "accent": "#ffe6ff"},
  {"id": 22, "name": "Supernova", "emoji": "💥", "rarity": "epic", "price": 2500, "color": "#ff8800", "ring": false, "glow": "#ffcc00", "desc": "Explosão estelar", "pattern": "plasma", "accent": "#fff2a0"},
  {"id": 23, "name": "Planeta Cristal", "emoji": "💎", "rarity": "epic", "price": 1800, "color": "#88eeff", "ring": false, "glow": "#aaffff", "desc": "Translúcido e raro", "pattern": "crystal", "accent": "#ffffff"},
  {"id": 24, "name": "Planeta Sombra", "emoji": "🌑", "rarity": "epic", "price": 1600, "color": "#222244", "ring": false, "glow": "#4444aa", "desc": "Escuridão total", "pattern": "nebula", "accent": "#5b5bd6"},
  {"id": 25, "name": "Estrela Nêutron", "emoji": "💫", "rarity": "epic", "price": 2200, "color": "#ffffff", "ring": false, "glow": "#88aaff", "desc": "Ultra-densa e rápida", "pattern": "swirl", "accent": "#88aaff"},
  {"id": 26, "name": "Planeta Aurora", "emoji": "🌌", "rarity": "epic", "price": 1700, "color": "#44ffcc", "ring": false, "glow": "#88ffee", "desc": "Luzes polares", "pattern": "aurora", "accent": "#b388ff"},
  {"id": 27, "name": "Planeta Tempestade", "emoji": "🌀", "rarity": "epic", "price": 1900, "color": "#6688cc", "ring": false, "glow": "#88aaff", "desc": "Furacão eterno", "pattern": "storm", "accent": "#d8e8ff"},
  {"id": 28, "name": "Anã Vermelha", "emoji": "❤️", "rarity": "epic", "price": 1600, "color": "#cc2200", "ring": false, "glow": "#ff4400", "desc": "Estrela em brasa", "pattern": "plasma", "accent": "#ff8844"},
  {"id": 29, "name": "Planeta Fantasma", "emoji": "👻", "rarity": "epic", "price": 2000, "color": "#eeeeff", "ring": false, "glow": "#aaaaff", "desc": "Semitransparente", "pattern": "nebula", "accent": "#aaaaff"},
  {"id": 30, "name": "Galáxia", "emoji": "🌌", "rarity": "legendary", "price": 5000, "color": "#cc88ff", "ring": true, "glow": "#ff88ff", "desc": "Uma galáxia inteira", "pattern": "galaxy", "accent": "#ff9ce8"},
  {"id": 31, "name": "Big Bang", "emoji": "✨", "rarity": "legendary", "price": 8000, "color": "#ffffff", "ring": false, "glow": "#ffffff", "desc": "O início de tudo", "pattern": "sparkle", "accent": "#ffd24a"},
  {"id": 32, "name": "Universo", "emoji": "🔭", "rarity": "legendary", "price": 10000, "color": "#000088", "ring": true, "glow": "#0044ff", "desc": "Contém tudo", "pattern": "galaxy", "accent": "#66aaff"},
  {"id": 33, "name": "Deus Cósmico", "emoji": "👁️", "rarity": "legendary", "price": 15000, "color": "#ffdd00", "ring": true, "glow": "#ffff00", "desc": "Além da compreensão", "pattern": "eye", "accent": "#6b3fd6"},
  {"id": 34, "name": "Dragão Estelar", "emoji": "🐉", "rarity": "legendary", "price": 7000, "color": "#ff4400", "ring": false, "glow": "#ff8800", "desc": "Lenda do cosmos", "pattern": "scales", "accent": "#ffcc33"},
  {"id": 35, "name": "Sobrevivente", "emoji": "🛡️", "rarity": "earned", "price": 0, "color": "#44aa88", "ring": false, "glow": "#66ccaa", "desc": "Sobreviva 5 min", "pattern": "metal", "accent": "#cfe6dd", "unlockKey": "survive5"},
  {"id": 36, "name": "Devorador", "emoji": "👅", "rarity": "earned", "price": 0, "color": "#ff6644", "ring": false, "glow": "#ff8866", "desc": "Coma 50 inimigos", "pattern": "swirl", "accent": "#ffd0c0", "unlockKey": "eat50"},
  {"id": 37, "name": "Massivo", "emoji": "⚖️", "rarity": "earned", "price": 0, "color": "#ddaa44", "ring": false, "glow": "#ffcc66", "desc": "Massa ≥ 5.000", "pattern": "stripes", "accent": "#fff0c0", "unlockKey": "mass5000"},
  {"id": 38, "name": "Divisor", "emoji": "✂️", "rarity": "earned", "price": 0, "color": "#88aaff", "ring": false, "glow": "#aaccff", "desc": "Divida 100 vezes", "pattern": "checker", "accent": "#dfe8ff", "unlockKey": "split100"},
  {"id": 39, "name": "Campeão", "emoji": "🏆", "rarity": "earned", "price": 0, "color": "#ffcc00", "ring": true, "glow": "#ffee44", "desc": "Nº1 por 3 minutos", "pattern": "metal", "accent": "#fff0b0", "unlockKey": "top1_3min"},
  {"id": 40, "name": "Veterano", "emoji": "🎖️", "rarity": "earned", "price": 0, "color": "#cc8844", "ring": false, "glow": "#ddaa66", "desc": "10 partidas jogadas", "pattern": "metal", "accent": "#f0d0a0", "unlockKey": "games10"},
  {"id": 41, "name": "Caçador", "emoji": "🎯", "rarity": "earned", "price": 0, "color": "#ff4488", "ring": false, "glow": "#ff66aa", "desc": "Coma 10 bots", "pattern": "rings2", "accent": "#ffd0e0", "unlockKey": "eatbots10"},
  {"id": 42, "name": "Ejector", "emoji": "💨", "rarity": "earned", "price": 0, "color": "#44ccff", "ring": false, "glow": "#66eeff", "desc": "Ejete 200 vezes", "pattern": "swirl", "accent": "#d0f4ff", "unlockKey": "eject200"},
  {"id": 43, "name": "Explorador", "emoji": "🗺️", "rarity": "earned", "price": 0, "color": "#88cc44", "ring": false, "glow": "#aaee66", "desc": "Explore todo o mapa", "pattern": "continents", "accent": "#d8b271", "unlockKey": "explore4"},
  {"id": 44, "name": "Imparável", "emoji": "🌪️", "rarity": "earned", "price": 0, "color": "#cc44ff", "ring": false, "glow": "#ee66ff", "desc": "5 abates sem morrer", "pattern": "storm", "accent": "#ffd0ff", "unlockKey": "streak5"},
  {"id": 45, "name": "???", "emoji": "❓", "rarity": "secret", "price": 0, "color": "#333355", "ring": false, "glow": "#555588", "desc": "Segredo oculto", "pattern": "plain", "unlockKey": "secret1"},
  {"id": 46, "name": "???", "emoji": "❓", "rarity": "secret", "price": 0, "color": "#333355", "ring": false, "glow": "#555588", "desc": "Segredo oculto", "pattern": "plain", "unlockKey": "secret2"},
  {"id": 47, "name": "???", "emoji": "❓", "rarity": "secret", "price": 0, "color": "#333355", "ring": false, "glow": "#555588", "desc": "Segredo oculto", "pattern": "plain", "unlockKey": "secret3"},
  {"id": 48, "name": "???", "emoji": "❓", "rarity": "secret", "price": 0, "color": "#333355", "ring": false, "glow": "#555588", "desc": "Segredo oculto", "pattern": "plain", "unlockKey": "secret4"},
  {"id": 49, "name": "Lenda Suprema", "emoji": "🌟", "rarity": "legendary", "price": 20000, "color": "#ffff88", "ring": true, "glow": "#ffffff", "desc": "O mais raro de todos", "pattern": "sparkle", "accent": "#ffffff"},
  {"id": 50, "name": "Titã", "emoji": "🌫️", "rarity": "rare", "price": 700, "color": "#d9a441", "ring": false, "glow": "#ffd88a", "desc": "Lua de metano e névoa", "pattern": "clouds", "accent": "#ffe3a8"},
  {"id": 51, "name": "Europa", "emoji": "🧊", "rarity": "rare", "price": 750, "color": "#dfe8f5", "ring": false, "glow": "#bcd8ff", "desc": "Oceano sob o gelo", "pattern": "ice", "accent": "#7fb3ff"},
  {"id": 52, "name": "Io", "emoji": "🌋", "rarity": "rare", "price": 800, "color": "#ffd257", "ring": false, "glow": "#ffb020", "desc": "Vulcões sem descanso", "pattern": "lava", "accent": "#ff6a2a"},
  {"id": 53, "name": "Plutão", "emoji": "🤍", "rarity": "rare", "price": 650, "color": "#c9b7a8", "ring": false, "glow": "#e8dcd0", "desc": "Pequeno e teimoso", "pattern": "craters", "accent": "#8f7d70"},
  {"id": 54, "name": "Anel Duplo", "emoji": "💫", "rarity": "rare", "price": 900, "color": "#9fd3ff", "ring": true, "glow": "#d8f0ff", "desc": "Dois anéis, um planeta", "pattern": "rings2", "accent": "#ffffff"},
  {"id": 55, "name": "Xadrez Cósmico", "emoji": "♟️", "rarity": "rare", "price": 700, "color": "#e8e8e8", "ring": false, "glow": "#ffffff", "desc": "Vitória em oito casas", "pattern": "checker", "accent": "#333355"},
  {"id": 56, "name": "Recife Estelar", "emoji": "🐚", "rarity": "rare", "price": 850, "color": "#2fd6b4", "ring": false, "glow": "#7dffe4", "desc": "Corais que brilham no vácuo", "pattern": "nebula", "accent": "#ffd6a0"},
  {"id": 57, "name": "Cinturão de Ferro", "emoji": "⛓️", "rarity": "rare", "price": 900, "color": "#8d99ae", "ring": false, "glow": "#c8d4e6", "desc": "Casco de aço frio", "pattern": "metal", "accent": "#d8e2ef"},
  {"id": 58, "name": "Planeta Girassol", "emoji": "🌻", "rarity": "epic", "price": 1500, "color": "#ffc93c", "ring": false, "glow": "#ffe98a", "desc": "Sempre virado para a luz", "pattern": "plasma", "accent": "#ff8a3d"},
  {"id": 59, "name": "Tempestade Elétrica", "emoji": "🌩️", "rarity": "epic", "price": 1700, "color": "#4a4e8c", "ring": false, "glow": "#8f9bff", "desc": "Raios que não param", "pattern": "storm", "accent": "#ffe14a"},
  {"id": 60, "name": "Coração Púrpura", "emoji": "💜", "rarity": "epic", "price": 1600, "color": "#8b46d6", "ring": false, "glow": "#c98aff", "desc": "Bate no ritmo do cosmos", "pattern": "aurora", "accent": "#ff8ad6"},
  {"id": 61, "name": "Mundo Espelho", "emoji": "🪞", "rarity": "epic", "price": 1900, "color": "#cfd8e3", "ring": false, "glow": "#ffffff", "desc": "Reflete quem te olha", "pattern": "crystal", "accent": "#ffffff"},
  {"id": 62, "name": "Serpente Solar", "emoji": "🐍", "rarity": "epic", "price": 2000, "color": "#ff7a3d", "ring": false, "glow": "#ffb070", "desc": "Escamas de fogo", "pattern": "scales", "accent": "#ffd24a"},
  {"id": 63, "name": "Olho do Abismo", "emoji": "👁️‍🗨️", "rarity": "epic", "price": 2400, "color": "#1b2a4a", "ring": false, "glow": "#37d6c1", "desc": "Ele te viu primeiro", "pattern": "eye", "accent": "#37d6c1"},
  {"id": 64, "name": "Jardim Suspenso", "emoji": "🌿", "rarity": "epic", "price": 1800, "color": "#3fbf6f", "ring": false, "glow": "#8fe8a8", "desc": "Vida onde ninguém esperava", "pattern": "continents", "accent": "#2a7a4a"},
  {"id": 65, "name": "Vórtice Gelado", "emoji": "❄️", "rarity": "epic", "price": 2100, "color": "#7fd6ff", "ring": false, "glow": "#d8f4ff", "desc": "Um furacão congelado", "pattern": "swirl", "accent": "#ffffff"},
  {"id": 66, "name": "Núcleo Fundido", "emoji": "🔥", "rarity": "epic", "price": 2300, "color": "#ff4d2a", "ring": false, "glow": "#ff9a4a", "desc": "Rachado por dentro", "pattern": "lava", "accent": "#ffe14a"},
  {"id": 67, "name": "Constelação", "emoji": "🔯", "rarity": "epic", "price": 1900, "color": "#2b2a6b", "ring": false, "glow": "#8f9bff", "desc": "Um mapa do céu", "pattern": "sparkle", "accent": "#ffe98a"},
  {"id": 68, "name": "Nebulosa Dourada", "emoji": "🥇", "rarity": "legendary", "price": 5000, "color": "#ffcf4a", "ring": false, "glow": "#fff0a0", "desc": "Poeira que virou ouro", "pattern": "nebula", "accent": "#ff7a3d"},
  {"id": 69, "name": "Espiral Prateada", "emoji": "🌪️", "rarity": "legendary", "price": 6000, "color": "#dfe6ef", "ring": true, "glow": "#ffffff", "desc": "Braços de prata girando", "pattern": "galaxy", "accent": "#7fb3ff"},
  {"id": 70, "name": "Coroa Solar", "emoji": "👑", "rarity": "legendary", "price": 9000, "color": "#ffb02e", "ring": true, "glow": "#ffe9a8", "desc": "A coroa de uma estrela", "pattern": "plasma", "accent": "#fff6c9"},
  {"id": 71, "name": "Aurora Eterna", "emoji": "🎆", "rarity": "legendary", "price": 12000, "color": "#35e0c0", "ring": true, "glow": "#a8fff0", "desc": "A noite que nunca apaga", "pattern": "aurora", "accent": "#b388ff"},
  {"id": 72, "name": "Dragão de Obsidiana", "emoji": "🐲", "rarity": "legendary", "price": 16000, "color": "#241a3a", "ring": false, "glow": "#ff4d2a", "desc": "Escamas de vidro vulcânico", "pattern": "scales", "accent": "#ff4d2a"},
  {"id": 73, "name": "Sentinela", "emoji": "⚔️", "rarity": "earned", "price": 0, "color": "#6b8cff", "ring": false, "glow": "#b8caff", "desc": "Sobreviva 10 min numa vida", "pattern": "metal", "accent": "#dfe8ff", "unlockKey": "survive10"},
  {"id": 74, "name": "Colosso", "emoji": "🗿", "rarity": "earned", "price": 0, "color": "#a8b0c0", "ring": false, "glow": "#dfe4ee", "desc": "Alcance massa 10.000", "pattern": "craters", "accent": "#6b7488", "unlockKey": "mass10000"}
];
export const SKIN_BY_ID=new Map(SKINS.map(s=>[s.id,s]));
export const skinById=id=>SKIN_BY_ID.get(id)||SKINS[0];
export const isPurchasable=s=>s.price>0&&!s.unlockKey;
